data:
  dataset: "BTCV"
  data_dir: "../medopenseg/datasets/BTCV/"
  split_json: "swin_unetr_btcv_dataset_0.json"

model:
  in_channels: 1
  out_channels: 11  # Background (0) + 10 Known Organs. Unseen are ignored.
  feature_size: 48  
  embed_dim_final: 128 # Matches Memory Bank feature_dim

training:
  batch_size: 2
  lr: 1e-4
  max_iterations: 30000
  eval_num: 100 # Validate every 500 steps (10 is too frequent for 3D)
  checkpoint_dir: "./outputs/btcv/memory_energy3"
  pretrained_weights: "./weights/model_swinvit.pt"
  
  # Memory Bank Settings
  use_memory_bank: True  
  memory_size: 500
  
  resume: False